version: '2'

networks:
  lemiseqnet:
    driver: bridge

services:
  front_end:
    build: .
    command: bash -c 'sleep 30s && npm start'
    ports:
      - 4200:4200
    volumes:
      - ./:/src
    # env_file:
    # - ./infra/lemiseq_auth.env
    networks:
    - lemiseqnet