version: '2'

networks:
  lemiseqnet:
    driver: bridge

services:
  lemiseq_auth:
    build: .
    command: bash -c 'sleep 30s && python service.py'
    ports:
      - 5000:5000
    volumes:
      - ./:/src
    env_file:
    - ./infra/lemiseq_auth.env
    networks:
    - lemiseqnet