version: '2'

networks:
  lemiseqnet:
    driver: bridge

services:
  mongo:
    image: aashreys/mongo-auth:latest
    ports:
      - 27021:27017
    env_file: ./infra/mongo.env
    networks:
      - lemiseqnet
  bioprocess:
    build: .
    command: bash -c 'sleep 20 && python service.py'
    ports:
    - 5001:5001
    volumes:
    - ./:/src
    env_file:
    - ./infra/bioprocess.env
    networks:
    - lemiseqnet
    depends_on:
    - mongo
